import { db } from "./index";
import { products } from "./schema";


const MAKES_MODELS: Record<string, Record<string, string[]>> = {
  Honda: {
    Civic: ["LX", "EX", "Sport", "Si", "Type R"],
    Accord: ["LX", "Sport", "EX-L", "Touring"],
    "CR-V": ["LX", "EX", "EX-L", "Touring"],
  },
  Toyota: {
    Camry: ["LE", "SE", "XLE", "TRD"],
    Corolla: ["L", "LE", "SE", "XSE"],
    RAV4: ["LE", "XLE", "Adventure", "TRD Off-Road"],
    Supra: ["2.0", "3.0", "3.0 Premium"],
  },
  Ford: {
    Mustang: ["EcoBoost", "GT", "Mach 1", "Shelby GT500"],
    F150: ["XL", "XLT", "Lariat", "Platinum"],
    Focus: ["S", "SE", "ST", "RS"],
  },
  BMW: {
    "3 Series": ["330i", "M340i", "M3"],
    "5 Series": ["530i", "540i", "M5"],
    X3: ["sDrive30i", "xDrive30i", "M40i"],
  },
  Subaru: {
    WRX: ["Base", "Premium", "Limited"],
    BRZ: ["Premium", "Limited"],
    Impreza: ["Base", "Premium", "Sport", "Limited"],
  },
};

function generateFitment(count: number) {
  const fitment: { year: number; make: string; model: string; submodel: string }[] = [];
  const makes = Object.keys(MAKES_MODELS);
  for (let i = 0; i < count; i++) {
    const make = makes[Math.floor(Math.random() * makes.length)];
    const models = Object.keys(MAKES_MODELS[make]);
    const model = models[Math.floor(Math.random() * models.length)];
    const submodels = MAKES_MODELS[make][model];
    const submodel = submodels[Math.floor(Math.random() * submodels.length)];
    const year = 2015 + Math.floor(Math.random() * 11);
    fitment.push({ year, make, model, submodel });
  }
  return fitment;
}

const SEED_PRODUCTS = [
  {
    sku: "EXH-001",
    brand: "Borla",
    title: "Borla S-Type Cat-Back Exhaust System",
    description: "The Borla S-Type Cat-Back Exhaust System delivers an aggressive, throaty tone under acceleration while maintaining a refined, civilized sound at cruise. Constructed from high-quality T-304 stainless steel for lasting durability and corrosion resistance.",
    category: "Exhaust",
    price: "899.99",
    msrp: "1099.99",
    stockCount: 24,
    images: ["/images/exhaust-1.jpg"],
    features: ["T-304 Stainless Steel Construction", "Mandrel-Bent Tubing", "Million-Mile Warranty", "50-State Legal"],
    specs: { Material: "T-304 Stainless Steel", "Tip Style": "Dual Round Rolled Edge", "Tip Size": '4"', Sound: "Aggressive" },
    rating: "4.8",
    reviewCount: 342,
    isUniversal: false,
  },
  {
    sku: "EXH-002",
    brand: "MagnaFlow",
    title: "MagnaFlow Street Series Cat-Back Exhaust",
    description: "MagnaFlow Street Series exhaust system provides a deep, smooth tone with improved horsepower and torque. Features mandrel-bent stainless steel piping and straight-through perforated stainless steel core muffler.",
    category: "Exhaust",
    price: "749.99",
    msrp: "899.99",
    stockCount: 18,
    images: ["/images/exhaust-2.jpg"],
    features: ["Stainless Steel Construction", "Dyno-Tested Performance Gains", "Deep Smooth Tone", "Bolt-On Installation"],
    specs: { Material: "Stainless Steel", "Tip Style": "Polished Single", "Tip Size": '5"', Sound: "Deep & Smooth" },
    rating: "4.6",
    reviewCount: 218,
    isUniversal: false,
  },
  {
    sku: "SUS-001",
    brand: "KW",
    title: "KW V3 Coilover Suspension Kit",
    description: "KW V3 Coilovers feature independently adjustable rebound and compression damping, allowing fine-tuning of both comfort and performance. Stainless steel technology ensures long-lasting corrosion resistance.",
    category: "Suspension",
    price: "1899.99",
    msrp: "2199.99",
    stockCount: 8,
    images: ["/images/suspension-1.jpg"],
    features: ["Adjustable Rebound & Compression", "Stainless Steel Construction", "Height Adjustable", "TÜV Approved"],
    specs: { "Spring Rate Front": "Variable", "Spring Rate Rear": "Variable", "Ride Height Drop": '0.8"-2.0"', Adjustability: "Rebound + Compression" },
    rating: "4.9",
    reviewCount: 156,
    isUniversal: false,
  },
  {
    sku: "SUS-002",
    brand: "Bilstein",
    title: "Bilstein B8 5100 Series Shock Absorber Set",
    description: "Bilstein B8 5100 Series shocks provide ride height adjustment and improved damping performance. The monotube gas pressure design provides consistent fade-free performance.",
    category: "Suspension",
    price: "549.99",
    msrp: "649.99",
    stockCount: 32,
    images: ["/images/suspension-2.jpg"],
    features: ["Monotube Gas Pressure Technology", "Zinc-Coated Piston Rod", "Ride Height Adjustable", "Limited Lifetime Warranty"],
    specs: { Type: "Monotube", "Ride Height Adjustment": '0"-2.5"', Finish: "Zinc Plated", Warranty: "Limited Lifetime" },
    rating: "4.7",
    reviewCount: 289,
    isUniversal: false,
  },
  {
    sku: "BRK-001",
    brand: "Brembo",
    title: "Brembo GT Big Brake Kit - Front",
    description: "Brembo GT Big Brake Kit features 6-piston monoblock calipers with two-piece cross-drilled or slotted rotors. Provides dramatically improved braking performance and stunning visual appeal.",
    category: "Brakes",
    price: "2499.99",
    msrp: "2899.99",
    stockCount: 5,
    images: ["/images/brakes-1.jpg"],
    features: ["6-Piston Monoblock Calipers", "Two-Piece Rotors", "Stainless Steel Braided Lines", "High-Performance Pads Included"],
    specs: { "Rotor Diameter": '380mm (15")', "Caliper Pistons": "6", "Rotor Type": "Cross-Drilled / Slotted", "Pad Type": "High-Performance Ceramic" },
    rating: "4.9",
    reviewCount: 87,
    isUniversal: false,
  },
  {
    sku: "BRK-002",
    brand: "StopTech",
    title: "StopTech Sport Brake Kit",
    description: "StopTech Sport Brake Kit includes slotted rotors and high-performance brake pads for improved stopping power and fade resistance. Direct bolt-on installation.",
    category: "Brakes",
    price: "699.99",
    msrp: "849.99",
    stockCount: 22,
    images: ["/images/brakes-2.jpg"],
    features: ["Slotted Rotors", "Sport Performance Pads", "Stainless Steel Hardware", "Direct Bolt-On"],
    specs: { "Rotor Type": "Slotted", "Pad Compound": "Sport Performance", Position: "Front", Warranty: "90 Day" },
    rating: "4.5",
    reviewCount: 194,
    isUniversal: false,
  },
  {
    sku: "LGT-001",
    brand: "Morimoto",
    title: "Morimoto XB LED Headlights",
    description: "Morimoto XB LED headlights deliver unmatched output and a truly modern look. Features sequential turn signal, plug-and-play installation, and DOT/SAE compliance.",
    category: "Lighting",
    price: "1299.99",
    msrp: "1499.99",
    stockCount: 12,
    images: ["/images/lighting-1.jpg"],
    features: ["Sequential Turn Signals", "Plug-and-Play Install", "DOT/SAE Compliant", "UV-Resistant Polycarbonate Lens"],
    specs: { "Bulb Type": "LED", "Color Temperature": "6000K", Lumens: "4,800 per side", Certification: "DOT / SAE" },
    rating: "4.8",
    reviewCount: 267,
    isUniversal: false,
  },
  {
    sku: "LGT-002",
    brand: "Diode Dynamics",
    title: "Diode Dynamics SS3 Pro LED Fog Lights",
    description: "The SS3 Pro LED fog light kit delivers a massive upgrade over factory halogen fog lights. Features a precision TIR optic for optimal beam pattern.",
    category: "Lighting",
    price: "349.99",
    msrp: "399.99",
    stockCount: 45,
    images: ["/images/lighting-2.jpg"],
    features: ["TIR Optic Technology", "SAE/DOT Compliant", "Plug-and-Play Harness", "50,000 Hour Lifespan"],
    specs: { Output: "2,680 Raw Lumens", Pattern: "SAE Fog", "Color Temperature": "6000K", "IP Rating": "IP67" },
    rating: "4.7",
    reviewCount: 534,
    isUniversal: false,
  },
  {
    sku: "EXT-001",
    brand: "Seibon",
    title: "Seibon Carbon Fiber Hood - OEM Style",
    description: "Seibon carbon fiber hoods are crafted from 100% carbon fiber, significantly reducing weight compared to OEM steel hoods. OEM style maintains factory appearance with lightweight performance.",
    category: "Exterior & Aero",
    price: "899.99",
    msrp: "1099.99",
    stockCount: 6,
    images: ["/images/exterior-1.jpg"],
    features: ["100% Carbon Fiber", "UV-Resistant Clear Coat", "40% Weight Reduction", "OEM Mounting Points"],
    specs: { Material: "Carbon Fiber (2x2 Twill)", Weight: "~12 lbs", "Clear Coat": "UV Resistant", Fitment: "Direct Replacement" },
    rating: "4.6",
    reviewCount: 92,
    isUniversal: false,
  },
  {
    sku: "EXT-002",
    brand: "APR Performance",
    title: "APR Performance Carbon Fiber Front Splitter",
    description: "APR Performance carbon fiber front splitter increases front downforce for improved high-speed stability. Wind tunnel tested and competition proven.",
    category: "Exterior & Aero",
    price: "649.99",
    msrp: "799.99",
    stockCount: 14,
    images: ["/images/exterior-2.jpg"],
    features: ["Wind Tunnel Tested", "Carbon Fiber Construction", "Support Rods Included", "Competition Proven"],
    specs: { Material: "Carbon Fiber", "Downforce Increase": "~45 lbs @ 100mph", "Support Rods": "Included", Finish: "Gloss Carbon" },
    rating: "4.4",
    reviewCount: 68,
    isUniversal: false,
  },
  {
    sku: "WHL-001",
    brand: "Enkei",
    title: 'Enkei RPF1 Lightweight Racing Wheel - 18x9.5"',
    description: "The Enkei RPF1 is the benchmark for lightweight racing wheels. MAT flow-forming process creates a wheel that is both incredibly light and exceptionally strong.",
    category: "Wheels",
    price: "379.99",
    msrp: "429.99",
    stockCount: 40,
    images: ["/images/wheels-1.jpg"],
    features: ["MAT Flow-Forming Technology", "JWL/VIA Certified", "Hub-Centric Design", "Multi-Spoke Design"],
    specs: { Size: "18x9.5", "Bolt Pattern": "5x114.3", Offset: "+38mm", Weight: "18.5 lbs" },
    rating: "4.9",
    reviewCount: 892,
    isUniversal: true,
  },
  {
    sku: "WHL-002",
    brand: "Volk Racing",
    title: 'Volk Racing TE37 Saga - 18x10"',
    description: "The iconic Volk Racing TE37 is one of the most recognized performance wheels in the world. Forged monoblock construction delivers ultimate strength-to-weight ratio.",
    category: "Wheels",
    price: "649.99",
    msrp: "749.99",
    stockCount: 16,
    images: ["/images/wheels-2.jpg"],
    features: ["Forged Monoblock Construction", "JWL/VIA Certified", "Iconic 6-Spoke Design", "Bronze Finish Available"],
    specs: { Size: "18x10", "Bolt Pattern": "5x114.3", Offset: "+35mm", Weight: "19.2 lbs" },
    rating: "5.0",
    reviewCount: 445,
    isUniversal: true,
  },
  {
    sku: "EXH-003",
    brand: "Invidia",
    title: "Invidia N1 Cat-Back Exhaust System",
    description: "Invidia N1 exhaust system features a straight-through design for maximum flow. SUS304 stainless steel construction with titanium tip for an aggressive race-inspired look.",
    category: "Exhaust",
    price: "599.99",
    msrp: "749.99",
    stockCount: 20,
    images: ["/images/exhaust-3.jpg"],
    features: ["SUS304 Stainless Steel", "Titanium Tip", "Straight-Through Design", "Mandrel-Bent Piping"],
    specs: { Material: "SUS304 Stainless Steel", "Tip Material": "Titanium", "Pipe Diameter": '3"', Sound: "Race Aggressive" },
    rating: "4.5",
    reviewCount: 312,
    isUniversal: false,
  },
  {
    sku: "SUS-003",
    brand: "Tein",
    title: "Tein Flex Z Coilover Kit",
    description: "Tein Flex Z coilovers offer 16 levels of damping force adjustment with a full-length ride height adjustment system. Excellent street performance at an accessible price point.",
    category: "Suspension",
    price: "799.99",
    msrp: "949.99",
    stockCount: 28,
    images: ["/images/suspension-3.jpg"],
    features: ["16-Level Damping Adjustment", "Full-Length Height Adjustment", "Dust Boot Included", "3-Year Warranty"],
    specs: { "Damping Levels": "16", "Height Range": '0.3"-2.8" drop', "Spring Rate F": "8 kg/mm", "Spring Rate R": "6 kg/mm" },
    rating: "4.4",
    reviewCount: 198,
    isUniversal: false,
  },
  {
    sku: "BRK-003",
    brand: "EBC",
    title: "EBC Yellowstuff Brake Pad Set",
    description: "EBC Yellowstuff brake pads are high-friction sport and race pads that work well from cold. Ideal for fast road driving and track day use.",
    category: "Brakes",
    price: "129.99",
    msrp: "159.99",
    stockCount: 65,
    images: ["/images/brakes-3.jpg"],
    features: ["High Friction from Cold", "Reduced Brake Dust", "Chamfered Edges", "ECE R90 Approved"],
    specs: { "Friction Coefficient": "0.42-0.55", "Temp Range": "0-900°C", Material: "Aramid Fiber Compound", Position: "Front" },
    rating: "4.3",
    reviewCount: 421,
    isUniversal: false,
  },
  {
    sku: "LGT-003",
    brand: "Rigid Industries",
    title: 'Rigid Industries SR-Series 20" LED Light Bar',
    description: "The Rigid SR-Series LED light bar delivers intense spot and flood combo beam pattern. Built to withstand the harshest off-road conditions.",
    category: "Lighting",
    price: "459.99",
    msrp: "549.99",
    stockCount: 30,
    images: ["/images/lighting-3.jpg"],
    features: ["Spot/Flood Combo Beam", "IP69K Waterproof", "50,000+ Hour LED Life", "Gore Pressure Equalizing Vent"],
    specs: { Length: '20"', LEDs: "40 (Hybrid Optics)", Lumens: "21,222 Raw", "IP Rating": "IP69K" },
    rating: "4.8",
    reviewCount: 176,
    isUniversal: true,
  },
  {
    sku: "EXT-003",
    brand: "Rocket Bunny",
    title: "Rocket Bunny V2 Wide Body Kit",
    description: "Rocket Bunny V2 wide body kit transforms your vehicle with aggressive fender flares and aero components. FRP construction for optimal fitment and durability.",
    category: "Exterior & Aero",
    price: "3299.99",
    msrp: "3799.99",
    stockCount: 3,
    images: ["/images/exterior-3.jpg"],
    features: ["Full Wide Body Conversion", "FRP Construction", "Hardware Included", "Professional Install Recommended"],
    specs: { Material: "FRP (Fiberglass Reinforced Plastic)", "Fender Width": "+50mm per side", Components: "8-Piece Kit", Finish: "Primer" },
    rating: "4.7",
    reviewCount: 45,
    isUniversal: false,
  },
  {
    sku: "WHL-003",
    brand: "BBS",
    title: 'BBS RS-GT Forged Wheel - 19x8.5"',
    description: "BBS RS-GT represents the pinnacle of forged wheel technology. Two-piece construction allows for custom offsets and widths while maintaining ultra-lightweight performance.",
    category: "Wheels",
    price: "899.99",
    msrp: "1049.99",
    stockCount: 10,
    images: ["/images/wheels-3.jpg"],
    features: ["Forged Two-Piece Construction", "Diamond Silver Finish", "Custom Offset Available", "TÜV Certified"],
    specs: { Size: "19x8.5", "Bolt Pattern": "5x120", Offset: "+32mm", Weight: "21.0 lbs" },
    rating: "4.8",
    reviewCount: 223,
    isUniversal: true,
  },
];

export async function seedDatabase() {
  // Check if products already exist
  const existing = await db.select({ id: products.id }).from(products).limit(1);
  if (existing.length > 0) return;

  for (const product of SEED_PRODUCTS) {
    const fitment = product.isUniversal ? [] : generateFitment(12 + Math.floor(Math.random() * 10));
    await db.insert(products).values({
      sku: product.sku,
      brand: product.brand,
      title: product.title,
      description: product.description,
      category: product.category,
      price: product.price,
      msrp: product.msrp,
      stockCount: product.stockCount,
      images: product.images as string[],
      features: product.features as string[],
      specs: product.specs as unknown as Record<string, string>,
      rating: product.rating,
      reviewCount: product.reviewCount,
      isUniversal: product.isUniversal,
      fitment,
    });
  }
}
